services:
  envoy:
    image: envoyproxy/envoy:v1.24-latest
    hostname: envoy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ../target/wasm32-unknown-unknown/release:/etc/envoy/proxy-wasm-plugins
    command:
      - "envoy"
      - "-c"
      - "/etc/envoy/envoy.yaml"
      - "--log-level"
      - "debug"
    network_mode: host