[package]
name = "clireg-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2"
proxy-wasm = "0.2.1"
log = "0.4.17"

[lib]
crate-type = ["cdylib", "rlib"]
